package XScripter;

public enum ScriptErrorCode 
{
	Unknown,
	InternalError,
	
	// syntax
	TypeIDExpected,
	IdentifierExpected,
	VarCannotBeVoid,
	IllegalChar,
	FnPostHdrExpected,
	FnAlreadyDef,
	LBraceExpected,
	RBraceExpected,
	UnknownIdent,
	Syntax,
	LBracketExpected,
	RBracketExpected,
	SemiColonExpected,
	GlobalInit,
	FieldInit,
	RightIndexBracketExpected,
	InvalidArrayType,
	ArraySizeExpected,
	InvalidArraySizeSpecifier,
	InvalidArrayIndexSpecifier,
	ReadonlyFunc,
	ReadonlyModify,
	
	
	// structure
	IncompatTypeOp,
	DuplicateIdentifier,
	OverloadNotFound,
	OverloadOnlyReturn,
	ReservedWordUsed,
	FuncDefMissing,
	VarNeverUsed,
	IllegalBreak,
	FuncCannotRetValue,
	EmptyBlock,
	UnreachableCode,
	MissingRet,
	VoidFuncInExpr,
	QuoteExpected,
	EndOfFile,
	UntilExpected,
	IncompleteReturnPath,
	ExternalFunc,
	 
	
	// classes, libs, externals
	ObjTypeExpected,
	FuncBodyInClass,
	ClassExpected,
	DelimiterExpected,
	InvalidClass,
	EmptyCtorNotFound,
	CannotInstantiateClass,
	ClassMismatch,
	IllegalDirective,
	DirectiveExpected,
	UnknownDirective,
	UnitDirectiveRecurence,
	DuplicateLibraryName,
	LibraryNotFound,
	LibraryNotCompiled,
	UnknownExtGlobalClassType,
	GenericObjectAccess,
	ClassIdentExpected,
	AbstractInstantiate,
	ClassAlreadyDefined,
	ClassDefMissing, 
	EventOutsideClass, 
	DuplicateEvent, 
	EventBody, 
	InvalidEvHandler, 
	ExtVarNotFound, 
	IllegalModifier, 
	NoLibraryFetcher, 
	StaticOutsideClass, 
	StaticAccessThroughInstance,
	
}
